---
name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  Build-ManyLinux-Wheels:
    runs-on: ubuntu-latest

    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Build Wheel
        run: docker run --rm -v `pwd`:/laszip-python -e PLAT=manylinux2014_x86_64 quay.io/pypa/manylinux2014_x86_64 /bin/sh /laszip-python/scripts/build-wheels-linux.sh

      - name: Upload wheels as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: "manylinux-wheels"
          path: "./wheelhouse/*manylinux*.whl"

  Build-ManyLinux-Arm64-Wheels:
    runs-on: ubuntu-latest

    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build Wheel
        run: docker run --rm -v `pwd`:/laszip-python --platform linux/arm64 -e PLAT=manylinux2014_aarch64 quay.io/pypa/manylinux2014_aarch64 /bin/sh /laszip-python/scripts/build-wheels-linux.sh

      - name: Upload wheels as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: "manylinux-arm64-wheels"
          path: "./wheelhouse/*manylinux*.whl"

  Build-MacOs-Wheels:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [ "3.8", "3.9", "3.10", "3.11" ]

    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Print Python info
        run: |
          which python${{ matrix.python-version }}
          python${{ matrix.python-version }} --version

      - name: Install dependencies (macos)
        run: |
          brew install laszip ninja
          python${{ matrix.python-version }} -m pip install --upgrade pip
          python${{ matrix.python-version }} -m pip install delocate

      - name: Build Wheels
        run: python${{ matrix.python-version }} -m pip wheel --wheel-dir dist .
        env:
            SKBUILD_CMAKE_ARGS: "-DCMAKE_OSX_DEPLOYMENT_TARGET=10.14"

      - name: Delocate wheels
        run: /bin/sh scripts/delocate-wheel.sh

      - name: Test importing the wheel
        run: |
          brew uninstall laszip
          whl_path="$(ls ./dist/*.whl | head -1)"
          python${{ matrix.python-version }} -m pip install $whl_path
          python${{ matrix.python-version }} -c "import laszip"

      - name: Upload wheel as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: "macOs-python${{ matrix.python-version }}"
          path: "./dist/*.whl"

  Build-Windows-Wheels:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [ "3.8", "3.9", "3.10", "3.11"]

    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Print Python info
        run: |
          py -${{ matrix.python-version }} --version

      - name: Install dependencies
        run: |
          vcpkg install laszip:x64-windows
          py -${{ matrix.python-version }} -m pip install --upgrade pip

      - name: Build Wheels
        shell: pwsh
        run: |
            py -${{ matrix.python-version }} -m pip wheel --wheel-dir dist .`
        env:
            SKBUILD_CMAKE_ARGS: "-DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake"

      - name: Test importing the wheel
        run: |
          vcpkg remove laszip:x64-windows
          $whl_path=ls ./dist/*.whl | Select-Object -Index 0
          py -${{ matrix.python-version }} -m pip install "$whl_path"
          py -${{ matrix.python-version }} -c "import laszip"

      - name: Upload wheel as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: "windows-python${{ matrix.python-version }}"
          path: "./dist/*.whl"
